
services:
  rok_dev:
#    build: .
    image: centos:7
    stdin_open: true  # эквивалентно -i
    tty: true         # эквивалентно -t
    privileged: true
    command: /usr/sbin/init
    ports:
      - "6379:6379"
      - "56379:56379"
#      - "7000:7000"
#      - "7010:7010"
#      - "8000:8000"
#      - "8010:8010"
#      - "9900-10000:9900-10000"
      - "10509:10509"
      - "19999:19999"
      - "44444-44446:44444-44446"
      - "56000-56011:56000-56011"
      - "57000-57011:57000-57011"
      - "58000-58011:58000-58011"
      - "58111:58111"
      - "58888:58888"
    volumes:
      - ./work:/root/rok-server/
    networks:
      - my-network

networks:
  my-network:
